# GitHub Actions CI Workflow

name: CI

# Controls when the action will run.
# For GITHUB_TOKEN permissions, see the loging section of the documentation: https://docs.github.com/en/actions/security-guides/automatic-token-authentication-to-access-github-related-resources

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds, tests, and lints the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest build twine black isort
          pip install -e .[dev] # Install project in editable mode with dev dependencies

      # Run linters and formatters
      - name: Run linters and formatters
        run: |
          ruff check .
          black --check .
          isort --check-only .

      # Run tests
      - name: Run tests
        run: |
          pytest

      # Build the package
      - name: Build the package
        run: |
          python -m build
